    /**
     *	THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT THIS FILE.
     *
     **/ 
	package com.amdocs.bss.tool.aifAnalyser;
	import java.util.TimeZone;
	import com.amdocs.uif.datacomm.*;
	import com.amdocs.uif.action.*;
	import com.amdocs.uif.binding.*;
	import com.amdocs.uif.data.*;
	import com.amdocs.uif.widgets.*;
	import com.amdocs.uif.widgets.search.*;
	import com.amdocs.uif.widgets.search.hierarchy.*;
	import com.amdocs.uif.workspace.*;
	import com.amdocs.jgoodies.forms.layout.*;
	import amdocs.core.vo.VoFieldDef;
	import amdocs.core.vo.VoMetaData;
	import com.amdocs.uif.binding.*;
	import com.amdocs.uif.validation.*;
	import com.amdocs.uif.widgets.tree.*;
	import com.amdocs.uif.validation.*;
	import com.amdocs.uif.security.*;	
    

    public class AifAnalyserForm_Builder extends FormBuilder
    {


    	
    	protected	UifTabularDataModelInfra MapBindingTDM;
    	protected	UifDataModelInfra uifId1721384065884167;
    	protected	UifDataModelInfra uifId1701384065884167;
    	protected	VoFieldDef uifId1691384065884167;
    	protected	VoMetaData uifId1751384065884186;
    	protected	UifTabularDataModelInfra backends;
    	protected	UifTabularDataModelInfra Classdetails;
    	protected	VoMetaData uifId841374222506005;
    	protected	UifTabularDataModelInfra backupOperationTDM;
    	protected	VoMetaData uifId821374221644989;
    	protected	UifTabularDataModelInfra OperationsTDM;
    	protected	UifDataModelInfra ResourceDetail;
    	protected	UifDataModelInfra OpDetials;
    	protected	VoFieldDef uifId1441381322002972;
    	protected	VoFieldDef uifId1331381309392319;
    	protected	VoFieldDef uifId1041380870087874;
    	protected	VoFieldDef uifId1031380870087874;
    	protected	VoFieldDef uifId971380869762626;
    	protected	VoFieldDef uifId961380869762626;
    	protected	VoMetaData uifId981380869762673;
    	protected	UifDataModelInfra inputDM;
    	protected	VoMetaData uifId491374213725583;
    	protected	UifTabularDataModelInfra propertyTDM_uifId481374213725583;
    	protected	VoMetaData uifId471374213713059;
    	protected	UifDataModelInfra rootNode;
    	protected	DatasetInfra dataset;
    	protected	AuthInfo uifId1821384188673519;
    	protected	LabelInfra lblMessage;
    	protected	AuthInfo uifId1611383203617437;
    	protected	ButtonInfra btnExport;
    	protected	AuthInfo uifId1591383070204400;
    	protected	ButtonInfra btnExpandAll;
    	protected	AuthInfo uifId861374480001804;
    	protected	LabelInfra Label_32;
    	protected	AuthInfo uifId761374220496891;
    	protected	PropertyBindingInfra uifId1221381229692852;
    	protected	BindingsInfra uifId1211381229692852;
    	protected	ComboBoxInfra cmbOperations;
    	protected	AuthInfo uifId781374220541654;
    	protected	ButtonInfra btnRead;
    	protected	AuthInfo uifId741374220447473;
    	protected	PropertyBindingInfra uifId1081380870126452;
    	protected	BindingsInfra uifId1071380870126452;
    	protected	TextFieldInfra txtPassword;
    	protected	AuthInfo uifId721374220442063;
    	protected	PropertyBindingInfra uifId1061380870109312;
    	protected	BindingsInfra uifId1051380870109312;
    	protected	TextFieldInfra txtUserName;
    	protected	AuthInfo uifId701374220428131;
    	protected	LabelInfra lblPwd;
    	protected	AuthInfo uifId681374220396532;
    	protected	LabelInfra lblUser;
    	protected	AuthInfo uifId661374220341490;
    	protected	TextFieldInfra txtInstance;
    	protected	AuthInfo uifId641374220309964;
    	protected	LabelInfra lblColon1;
    	protected	AuthInfo uifId621374220225887;
    	protected	TextFieldInfra txtPort;
    	protected	AuthInfo uifId601374220203585;
    	protected	LabelInfra lblColon2;
    	protected	AuthInfo uifId581374220137495;
    	protected	TextFieldInfra txtServer;
    	protected	AuthInfo uifId561374220106786;
    	protected	LabelInfra lblUrl1;
    	protected	AuthInfo uifId541374220056377;
    	protected	PanelInfra Panel_16;
    	protected	AuthInfo uifId511374216553833;
    	protected	TextFieldInfra txtQuickSearch;
    	protected	AuthInfo uifId191374153052404;
    	protected	ButtonInfra btnAnalyse;
    	protected	DataTransferEvents uifId151374152531343;
    	protected	MenuInfra uifId411374213392778;
    	protected	AuthInfo uifId421374213392789;
    	protected	PropertyBindingInfra uifId441374213420526;
    	protected	BindingsInfra uifId431374213420526;
    	protected	TreeNodeInfra uifId401374213392778;
    	protected	TreeNodeTemplateInfra uifId391374213392778;
    	protected	MenuInfra uifId301374156606420;
    	protected	AuthInfo uifId311374156626987;
    	protected	PropertyBindingInfra uifId451374213532271;
    	protected	BindingsInfra uifId321374157163129;
    	protected	TreeNodeInfra uifId291374156606420;
    	protected	TreeNodeTemplateInfra uifId281374156606420;
    	protected	MenuInfra uifId131374152530776;
    	protected	AuthInfo uifId381374210997507;
    	protected	TreeNodeInfra uifId121374152530776;
    	protected	TreeNodeTemplateInfra uifId111374152530775;
    	protected	AuthInfo uifId141374152531304;
    	protected	TreeInfra treeAifOperation;
    	protected	AuthInfo uifId81374151879674;
    	protected	PanelInfra root;
    	protected	PostSubmitActionInfra uifId1271381304795848;
    	protected	ResponseMapItemInfra uifId1511381992391574;
    	protected	ResponseDataMapInfra uifId1481381918944050;
    	protected	RequestMapItemInfra uifId1491381920156339;
    	protected	RequestMapItemInfra uifId1341381310765325;
    	protected	RequestDataMapInfra uifId1351381310766747;
    	protected	ValidationInfoInfra uifId1261381304795832;
    	protected	AuthInfo uifId1251381304795832;
    	protected	SubmitActionInfra getItemDetails;
    	protected	PostSubmitActionInfra uifId941380869040240;
    	protected	ResponseMapItemInfra uifId1191381229454479;
    	protected	ResponseDataMapInfra uifId1201381229455182;
    	protected	RequestMapItemInfra uifId1631384021167358;
    	protected	RequestMapItemInfra uifId1621384021150636;
    	protected	RequestMapItemInfra uifId1151381225043382;
    	protected	RequestMapItemInfra uifId1141381225031492;
    	protected	RequestDataMapInfra uifId1161381225043960;
    	protected	ValidationInfoInfra uifId931380869040240;
    	protected	AuthInfo uifId921380869040240;
    	protected	SubmitActionInfra getOperationsDetail;
    	protected	PostSubmitActionInfra uifId901380869034865;
    	protected	ResponseMapItemInfra uifId1171381228586953;
    	protected	ResponseDataMapInfra uifId1181381228587672;
    	protected	RequestMapItemInfra uifId1121381224897617;
    	protected	RequestMapItemInfra uifId1111381224879118;
    	protected	RequestMapItemInfra uifId1101381224862149;
    	protected	RequestDataMapInfra uifId1131381224898461;
    	protected	ValidationInfoInfra uifId891380869034865;
    	protected	AuthInfo uifId881380869034865;
    	protected	SubmitActionInfra getOperationsList;
    	protected	WorkspaceEvents uifId91374151899633;
    	
	    /**
	     * Constructs a new FormBuilder.
	     */
	    public AifAnalyserForm_Builder(AifAnalyserForm form)
	    {
	    	super(form);
				    	
	    	addResourceBundle("com.amdocs.bss.tool.aifAnalyser.AifAnalyserForm");
	    		
	    }
    	
    	
    	
    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createControls()
    	{

			root = (PanelInfra)form.getRootPanel();	
			treeAifOperation=AbstractWidgetFactory.getInstance().createTree(this);	
				
			uifId111374152530775 = (TreeNodeTemplateInfra)treeAifOperation.getRootTemplate();	
			uifId121374152530776=AbstractWidgetFactory.getInstance().createTreeNodeControl(this);	
				
			uifId291374156606420=AbstractWidgetFactory.getInstance().createTreeNodeControl(this);	
				
			uifId401374213392778=AbstractWidgetFactory.getInstance().createTreeNodeControl(this);	
				
			btnAnalyse=AbstractWidgetFactory.getInstance().createButton(this);	
				
			txtQuickSearch=AbstractWidgetFactory.getInstance().createTextField(this);	
				
			Panel_16=AbstractWidgetFactory.getInstance().createPanel(this);	
				
			lblUrl1=AbstractWidgetFactory.getInstance().createLabel(this);	
				
			txtServer=AbstractWidgetFactory.getInstance().createTextField(this);	
				
			lblColon2=AbstractWidgetFactory.getInstance().createLabel(this);	
				
			txtPort=AbstractWidgetFactory.getInstance().createTextField(this);	
				
			lblColon1=AbstractWidgetFactory.getInstance().createLabel(this);	
				
			txtInstance=AbstractWidgetFactory.getInstance().createTextField(this);	
				
			lblUser=AbstractWidgetFactory.getInstance().createLabel(this);	
				
			lblPwd=AbstractWidgetFactory.getInstance().createLabel(this);	
				
			txtUserName=AbstractWidgetFactory.getInstance().createTextField(this);	
				
			txtPassword=AbstractWidgetFactory.getInstance().createTextField(this);	
				
			btnRead=AbstractWidgetFactory.getInstance().createButton(this);	
				
			cmbOperations=AbstractWidgetFactory.getInstance().createComboBox(this);	
				
			Label_32=AbstractWidgetFactory.getInstance().createLabel(this);	
				
			btnExpandAll=AbstractWidgetFactory.getInstance().createButton(this);	
				
			btnExport=AbstractWidgetFactory.getInstance().createButton(this);	
				
			lblMessage=AbstractWidgetFactory.getInstance().createLabel(this);	
			
			    			
    	}
    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createActionElements()
    	{

    				
    		getOperationsList = new SubmitActionInfra(this ,"getOperationsList");
		
    		getOperationsDetail = new SubmitActionInfra(this ,"getOperationsDetail");
		
    		getItemDetails = new SubmitActionInfra(this ,"getItemDetails");

			    			
    	}
    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createDataModels()
    	{

    			
			dataset=(DatasetInfra)form.getDataset();	
				
			rootNode=(UifDataModelInfra)dataset.createDataModel("rootNode",UifDataset.DataModelType.DATAMODEL,true);	
				
			dataset.addDataModel(rootNode);	
			propertyTDM_uifId481374213725583=(UifTabularDataModelInfra)dataset.createDataModel("propertyTDM",UifDataset.DataModelType.TABULARDATAMODEL,true);	
				
			inputDM=(UifDataModelInfra)dataset.createDataModel("inputDM",UifDataset.DataModelType.DATAMODEL,true);	
				
			dataset.addDataModel(inputDM);	
			OpDetials=(UifDataModelInfra)dataset.createDataModel("OpDetials",UifDataset.DataModelType.DATAMODEL,"crm","com.amdocs.aif.datamodel.Operation",true);	
				
			dataset.addDataModel(OpDetials);	
			ResourceDetail=(UifDataModelInfra)dataset.createDataModel("ResourceDetail",UifDataset.DataModelType.DATAMODEL,"crm","com.amdocs.aif.consumer.ResourceDesc",true);	
				
			dataset.addDataModel(ResourceDetail);	
			OperationsTDM=(UifTabularDataModelInfra)dataset.createDataModel("OperationsTDM",UifDataset.DataModelType.TABULARDATAMODEL,true);	
				
			dataset.addDataModel(OperationsTDM);	
			backupOperationTDM=(UifTabularDataModelInfra)dataset.createDataModel("backupOperationTDM",UifDataset.DataModelType.TABULARDATAMODEL,true);	
				
			dataset.addDataModel(backupOperationTDM);	
			Classdetails=(UifTabularDataModelInfra)dataset.createDataModel("Classdetails",UifDataset.DataModelType.TABULARDATAMODEL,"crm","com.amdocs.bss.tool.AifAnalyser.ClassDetails",true);	
				
			dataset.addDataModel(Classdetails);	
			backends=(UifTabularDataModelInfra)dataset.createDataModel("backends",UifDataset.DataModelType.TABULARDATAMODEL,true);	
				
			dataset.addDataModel(backends);	
			uifId1701384065884167=(UifDataModelInfra)dataset.createDataModel(null,UifDataset.DataModelType.DATAMODEL,true);	
				
			uifId1721384065884167=(UifDataModelInfra)dataset.createDataModel(null,UifDataset.DataModelType.DATAMODEL,true);	
				
			MapBindingTDM=(UifTabularDataModelInfra)dataset.createDataModel("MapBindingTDM",UifDataset.DataModelType.TABULARDATAMODEL,"crm","com.amdocs.bss.tool.AifAnalyser.OperationDetails",true);	
				
			dataset.addDataModel(MapBindingTDM);
			    			
    	}
   	    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createDataCommElements()
    	{

    		
			    			
    	}

    	
    	/**
	     * This method initializes DataModel,Tabular DataModel, Tree control properties
	     */
    	protected void preInitNonTranslatableProperties()
    	{
    		
			root.setName("root");
			treeAifOperation.setWordWrapOn(true);
			treeAifOperation.setHighlightMode(UifTree.HighlightMode.SINGLE);
			treeAifOperation.setName("treeAifOperation");
			uifId111374152530775.setName("Root");
			uifId111374152530775.setDataModelPath("rootNode");
			uifId111374152530775.setAutoExpanded(true);
			uifId121374152530776.setText(getString("uifId121374152530776.text"));
			uifId121374152530776.setName("TreeNodeControl_3");
			uifId111374152530775.setNodeControl(uifId121374152530776);	
			uifId281374156606420 = new TreeNodeTemplateInfra();
			
			uifId281374156606420.setName("OpProp");
			uifId281374156606420.setDataModelPath("propertyTDM");
			uifId281374156606420.setAutoExpanded(true);
			uifId111374152530775.addTreeNodeTemplate(uifId281374156606420);
			uifId291374156606420.setActivationAction(getItemDetails);
			uifId291374156606420.setName("TreeNodeControl_7");
			uifId281374156606420.setNodeControl(uifId291374156606420);	
			uifId391374213392778 = new TreeNodeTemplateInfra();
			
			uifId391374213392778.setRecursiveTemplateName("OpProp");
			uifId391374213392778.setName("recursiveNode");
			uifId281374156606420.addTreeNodeTemplate(uifId391374213392778);
			uifId401374213392778.setText(getString("uifId401374213392778.text"));
			uifId401374213392778.setOpenIcon(getString("uifId401374213392778.openIcon"));
			uifId401374213392778.setLeafIcon(getString("uifId401374213392778.leafIcon"));
			uifId401374213392778.setClosedIcon(getString("uifId401374213392778.closedIcon"));
			uifId401374213392778.setName("TreeNodeControl_13");
			uifId391374213392778.setNodeControl(uifId401374213392778);
			btnAnalyse.setName("btnAnalyse");
			txtQuickSearch.setName("txtQuickSearch");
			Panel_16.setName("Panel_16");
			lblUrl1.setName("lblUrl1");
			txtServer.setName("txtServer");
			lblColon2.setName("lblColon2");
			txtPort.setName("txtPort");
			lblColon1.setName("lblColon1");
			txtInstance.setName("txtInstance");
			lblUser.setName("lblUser");
			lblPwd.setName("lblPwd");
			txtUserName.setName("txtUserName");
			txtPassword.setName("txtPassword");
			btnRead.setName("btnRead");
			cmbOperations.setName("cmbOperations");
			Label_32.setName("Label_32");
			btnExpandAll.setName("btnExpandAll");
			btnExport.setName("btnExport");
			lblMessage.setName("lblMessage");	
			uifId471374213713059 = new VoMetaData();
			
			uifId471374213713059.setName("rootNode");
			rootNode.setMetadata(uifId471374213713059);	rootNode.setValue("propertyTDM" ,propertyTDM_uifId481374213725583);
    		
			uifId491374213725583 = new VoMetaData();
			
			uifId491374213725583.setName("TestTDM");
			propertyTDM_uifId481374213725583.setMetadata(uifId491374213725583);	
			uifId981380869762673 = new VoMetaData();
			
			uifId981380869762673.setName("inputDM");
			inputDM.setMetadata(uifId981380869762673);	
			uifId961380869762626 = new VoFieldDef();
			
			uifId961380869762626.setName("URL");
			uifId961380869762626.setDataType("java.lang.String");
			uifId981380869762673.addField(uifId961380869762626);	
			uifId971380869762626 = new VoFieldDef();
			
			uifId971380869762626.setName("Operation");
			uifId971380869762626.setDataType("java.lang.String");
			uifId981380869762673.addField(uifId971380869762626);	
			uifId1031380870087874 = new VoFieldDef();
			
			uifId1031380870087874.setName("user");
			uifId1031380870087874.setDataType("java.lang.String");
			uifId981380869762673.addField(uifId1031380870087874);	
			uifId1041380870087874 = new VoFieldDef();
			
			uifId1041380870087874.setName("password");
			uifId1041380870087874.setDataType("java.lang.String");
			uifId981380869762673.addField(uifId1041380870087874);	
			uifId1331381309392319 = new VoFieldDef();
			
			uifId1331381309392319.setName("item");
			uifId1331381309392319.setDataType("java.lang.String");
			uifId981380869762673.addField(uifId1331381309392319);	
			uifId1441381322002972 = new VoFieldDef();
			
			uifId1441381322002972.setName("bindingType");
			uifId1441381322002972.setDataType("java.lang.String");
			uifId981380869762673.addField(uifId1441381322002972);    	inputDM.setStringValue("user","sa");
    	    	inputDM.setStringValue("password","sa");
    		
			uifId821374221644989 = new VoMetaData();
			
			uifId821374221644989.setName("OperationsTDM");
			OperationsTDM.setMetadata(uifId821374221644989);	
			uifId841374222506005 = new VoMetaData();
			
			uifId841374222506005.setName("backupOperationTDM");
			backupOperationTDM.setMetadata(uifId841374222506005);	
			uifId1751384065884186 = new VoMetaData();
			
			uifId1751384065884186.setName("backends");
			backends.setMetadata(uifId1751384065884186);	
			uifId1691384065884167 = new VoFieldDef();
			
			uifId1691384065884167.setName("title");
			uifId1691384065884167.setDataType("java.lang.String");
			uifId1751384065884186.addField(uifId1691384065884167);	backends.addDataModel(uifId1701384065884167);
    	    	uifId1701384065884167.setStringValue("title","crm");
    		backends.addDataModel(uifId1721384065884167);
    	    	uifId1721384065884167.setStringValue("title","Ordering");
    	
    	}
    	
    	
    	/**
	     * Adds actions to the action set
	     */
    	protected void addToActionSet()
    	{
    		
    		((ActionSetInfra)this.form.getActionSet()).addAction(getItemDetails);
    		((ActionSetInfra)this.form.getActionSet()).addAction(getOperationsDetail);
    		((ActionSetInfra)this.form.getActionSet()).addAction(getOperationsList);
    		
    	}
    	
    	
    	/**
	     * Adds controls to control set
	     */
    	protected void addToControlSet()
    	{
    		
			((ControlSetInfra)this.form.getControlSet()).addControl(lblMessage);
    		((ControlSetInfra)this.form.getControlSet()).addControl(btnExport);
    		((ControlSetInfra)this.form.getControlSet()).addControl(btnExpandAll);
    		((ControlSetInfra)this.form.getControlSet()).addControl(Label_32);
    		((ControlSetInfra)this.form.getControlSet()).addControl(cmbOperations);
    		((ControlSetInfra)this.form.getControlSet()).addControl(btnRead);
    		((ControlSetInfra)this.form.getControlSet()).addControl(txtPassword);
    		((ControlSetInfra)this.form.getControlSet()).addControl(txtUserName);
    		((ControlSetInfra)this.form.getControlSet()).addControl(lblPwd);
    		((ControlSetInfra)this.form.getControlSet()).addControl(lblUser);
    		((ControlSetInfra)this.form.getControlSet()).addControl(txtInstance);
    		((ControlSetInfra)this.form.getControlSet()).addControl(lblColon1);
    		((ControlSetInfra)this.form.getControlSet()).addControl(txtPort);
    		((ControlSetInfra)this.form.getControlSet()).addControl(lblColon2);
    		((ControlSetInfra)this.form.getControlSet()).addControl(txtServer);
    		((ControlSetInfra)this.form.getControlSet()).addControl(lblUrl1);
    		((ControlSetInfra)this.form.getControlSet()).addControl(Panel_16);
    		((ControlSetInfra)this.form.getControlSet()).addControl(txtQuickSearch);
    		((ControlSetInfra)this.form.getControlSet()).addControl(btnAnalyse);
    		((ControlSetInfra)this.form.getControlSet()).addControl(treeAifOperation);
    		
    		    		
    	}
    	
    	/**
	     * Initializes App code variables
	     */
    	protected void initAppCodeVariables()
    	{
    			
    		((AifAnalyserForm)form).MapBindingTDM = MapBindingTDM;
      		((AifAnalyserForm)form).backends = backends;
      		((AifAnalyserForm)form).Classdetails = Classdetails;
      		((AifAnalyserForm)form).backupOperationTDM = backupOperationTDM;
      		((AifAnalyserForm)form).OperationsTDM = OperationsTDM;
      		((AifAnalyserForm)form).ResourceDetail = ResourceDetail;
      		((AifAnalyserForm)form).OpDetials = OpDetials;
      		((AifAnalyserForm)form).inputDM = inputDM;
      		((AifAnalyserForm)form).rootNode = rootNode;
      		((AifAnalyserForm)form).lblMessage = lblMessage;
      		((AifAnalyserForm)form).btnExport = btnExport;
      		((AifAnalyserForm)form).btnExpandAll = btnExpandAll;
      		((AifAnalyserForm)form).Label_32 = Label_32;
      		((AifAnalyserForm)form).cmbOperations = cmbOperations;
      		((AifAnalyserForm)form).btnRead = btnRead;
      		((AifAnalyserForm)form).txtPassword = txtPassword;
      		((AifAnalyserForm)form).txtUserName = txtUserName;
      		((AifAnalyserForm)form).lblPwd = lblPwd;
      		((AifAnalyserForm)form).lblUser = lblUser;
      		((AifAnalyserForm)form).txtInstance = txtInstance;
      		((AifAnalyserForm)form).lblColon1 = lblColon1;
      		((AifAnalyserForm)form).txtPort = txtPort;
      		((AifAnalyserForm)form).lblColon2 = lblColon2;
      		((AifAnalyserForm)form).txtServer = txtServer;
      		((AifAnalyserForm)form).lblUrl1 = lblUrl1;
      		((AifAnalyserForm)form).Panel_16 = Panel_16;
      		((AifAnalyserForm)form).txtQuickSearch = txtQuickSearch;
      		((AifAnalyserForm)form).btnAnalyse = btnAnalyse;
      		((AifAnalyserForm)form).treeAifOperation = treeAifOperation;
      		((AifAnalyserForm)form).getItemDetails = getItemDetails;
      		((AifAnalyserForm)form).getOperationsDetail = getOperationsDetail;
      		((AifAnalyserForm)form).getOperationsList = getOperationsList;
      		
    	}
    	
    	
    	/**
	     * Initializes the properties of Form Elements 
	     */
	     
    	protected void initNonTranslatableProperties()
    	{	
			uifId91374151899633 = new WorkspaceEvents();
			
			this.setWorkspaceEvents(uifId91374151899633);
			getOperationsList.setActionStartMethodName("getOperationsList_ActionStart");
			getOperationsList.setOperationType("AIF");
			getOperationsList.setOperationName("com.amdocs.bss.tool.AifAnalyser.AnalyseList");
			getOperationsList.setBackendId("crm");
			getOperationsList.setActionDoneMethodName("getOperationsList_ActionDone");
			uifId881380869034865 = (AuthInfo)getOperationsList.getAuthInfo();
			uifId891380869034865 = (ValidationInfoInfra)getOperationsList.getValidationInfo();
			uifId1131381224898461 = (RequestDataMapInfra)getOperationsList.getRequestDataMap();	
			uifId1101381224862149 = new RequestMapItemInfra();
			
			uifId1101381224862149.setTargetPath("Url");
			uifId1101381224862149.setFieldName("URL");
			uifId1101381224862149.setDataReference((UifDataModelInfra)inputDM);
			uifId1131381224898461.addRequestMapItem(uifId1101381224862149);	
			uifId1111381224879118 = new RequestMapItemInfra();
			
			uifId1111381224879118.setTargetPath("User");
			uifId1111381224879118.setFieldName("user");
			uifId1111381224879118.setDataReference((UifDataModelInfra)inputDM);
			uifId1131381224898461.addRequestMapItem(uifId1111381224879118);	
			uifId1121381224897617 = new RequestMapItemInfra();
			
			uifId1121381224897617.setTargetPath("Password");
			uifId1121381224897617.setFieldName("password");
			uifId1121381224897617.setDataReference((UifDataModelInfra)inputDM);
			uifId1131381224898461.addRequestMapItem(uifId1121381224897617);
			uifId1181381228587672 = (ResponseDataMapInfra)getOperationsList.getResponseDataMap();	
			uifId1171381228586953 = new ResponseMapItemInfra();
			
			uifId1171381228586953.setSourcePath("OperationArray");
			uifId1171381228586953.setDataReference((UifDataModelBase)OperationsTDM);
			uifId1181381228587672.addResponseMapItem(uifId1171381228586953);
			uifId901380869034865 = (PostSubmitActionInfra)getOperationsList.getPostSubmitAction();
			getOperationsDetail.setActionStartMethodName("getOperationsDetail_ActionStart");
			getOperationsDetail.setOperationType("AIF");
			getOperationsDetail.setOperationName("com.amdocs.bss.tool.AifAnalyser.AnalyseOperation");
			getOperationsDetail.setBackendId("crm");
			getOperationsDetail.setActionDoneMethodName("getOperationsDetail_ActionDone");
			uifId921380869040240 = (AuthInfo)getOperationsDetail.getAuthInfo();
			uifId931380869040240 = (ValidationInfoInfra)getOperationsDetail.getValidationInfo();
			uifId1161381225043960 = (RequestDataMapInfra)getOperationsDetail.getRequestDataMap();	
			uifId1141381225031492 = new RequestMapItemInfra();
			
			uifId1141381225031492.setTargetPath("OperationName");
			uifId1141381225031492.setFieldName("Operation");
			uifId1141381225031492.setDataReference((UifDataModelInfra)inputDM);
			uifId1161381225043960.addRequestMapItem(uifId1141381225031492);	
			uifId1151381225043382 = new RequestMapItemInfra();
			
			uifId1151381225043382.setTargetPath("Url");
			uifId1151381225043382.setFieldName("URL");
			uifId1151381225043382.setDataReference((UifDataModelInfra)inputDM);
			uifId1161381225043960.addRequestMapItem(uifId1151381225043382);	
			uifId1621384021150636 = new RequestMapItemInfra();
			
			uifId1621384021150636.setTargetPath("User");
			uifId1621384021150636.setFieldName("user");
			uifId1621384021150636.setDataReference((UifDataModelInfra)inputDM);
			uifId1161381225043960.addRequestMapItem(uifId1621384021150636);	
			uifId1631384021167358 = new RequestMapItemInfra();
			
			uifId1631384021167358.setTargetPath("Password");
			uifId1631384021167358.setFieldName("password");
			uifId1631384021167358.setDataReference((UifDataModelInfra)inputDM);
			uifId1161381225043960.addRequestMapItem(uifId1631384021167358);
			uifId1201381229455182 = (ResponseDataMapInfra)getOperationsDetail.getResponseDataMap();	
			uifId1191381229454479 = new ResponseMapItemInfra();
			
			uifId1191381229454479.setSourcePath("Operation");
			uifId1191381229454479.setDataReference((UifDataModelBase)OpDetials);
			uifId1201381229455182.addResponseMapItem(uifId1191381229454479);
			uifId941380869040240 = (PostSubmitActionInfra)getOperationsDetail.getPostSubmitAction();
			getItemDetails.setActionStartMethodName("getItemDetails_ActionStart");
			getItemDetails.setOperationType("AIF");
			getItemDetails.setOperationName("com.amdocs.bss.tool.AifAnalyser.AnalyseItem");
			getItemDetails.setBackendId("crm");
			getItemDetails.setActionDoneMethodName("getItemDetails_ActionDone");
			uifId1251381304795832 = (AuthInfo)getItemDetails.getAuthInfo();
			uifId1261381304795832 = (ValidationInfoInfra)getItemDetails.getValidationInfo();
			uifId1351381310766747 = (RequestDataMapInfra)getItemDetails.getRequestDataMap();	
			uifId1341381310765325 = new RequestMapItemInfra();
			
			uifId1341381310765325.setTargetPath("Item");
			uifId1341381310765325.setFieldName("item");
			uifId1341381310765325.setDataReference((UifDataModelInfra)inputDM);
			uifId1351381310766747.addRequestMapItem(uifId1341381310765325);	
			uifId1491381920156339 = new RequestMapItemInfra();
			
			uifId1491381920156339.setTargetPath("ValueMap");
			uifId1491381920156339.setDataReference((UifTabularDataModelInfra)MapBindingTDM);
			uifId1351381310766747.addRequestMapItem(uifId1491381920156339);
			uifId1481381918944050 = (ResponseDataMapInfra)getItemDetails.getResponseDataMap();	
			uifId1511381992391574 = new ResponseMapItemInfra();
			
			uifId1511381992391574.setSourcePath("elementArray");
			uifId1511381992391574.setDataReference((UifDataModelBase)Classdetails);
			uifId1481381918944050.addResponseMapItem(uifId1511381992391574);
			uifId1271381304795848 = (PostSubmitActionInfra)getItemDetails.getPostSubmitAction();
			uifId81374151879674 = (AuthInfo)root.getAuthInfo();	
			((javax.swing.JPanel)(root).getNativePanel()).setLayout(
				new FormLayout("76px,default:grow,default,default",
								"top:96px,top:default,top:default,top:default,top:default,top:default:grow"));
			treeAifOperation.setPostNodeExpandMethodName("treeAifOperation_PostNodeExpand");
			uifId141374152531304 = (AuthInfo)treeAifOperation.getAuthInfo();
			uifId381374210997507 = (AuthInfo)uifId121374152530776.getAuthInfo();
			uifId131374152530776 = (MenuInfra)uifId121374152530776.getContextualMenu();
			uifId131374152530776.setName("Menu_4");
			uifId321374157163129 = (BindingsInfra)uifId291374156606420.getBindings();	
			uifId451374213532271 = new PropertyBindingInfra();
			
			uifId451374213532271.setPropertyName("text");
			uifId451374213532271.setFieldName("name");
			uifId321374157163129.addPropertyBinding(uifId451374213532271);
			uifId311374156626987 = (AuthInfo)uifId291374156606420.getAuthInfo();
			uifId301374156606420 = (MenuInfra)uifId291374156606420.getContextualMenu();
			uifId301374156606420.setName("Menu_8");
			uifId431374213420526 = (BindingsInfra)uifId401374213392778.getBindings();	
			uifId441374213420526 = new PropertyBindingInfra();
			
			uifId441374213420526.setPropertyName("text");
			uifId441374213420526.setFieldName("name");
			uifId431374213420526.addPropertyBinding(uifId441374213420526);
			uifId421374213392789 = (AuthInfo)uifId401374213392778.getAuthInfo();
			uifId411374213392778 = (MenuInfra)uifId401374213392778.getContextualMenu();
			uifId411374213392778.setName("Menu_14");
			uifId151374152531343 = (DataTransferEvents)treeAifOperation.getDataTransferEvents();
			btnAnalyse.setAction(getOperationsDetail);
			btnAnalyse.setEnabled(false);
			uifId191374153052404 = (AuthInfo)btnAnalyse.getAuthInfo();
			txtQuickSearch.setEnabled(false);
			uifId511374216553833 = (AuthInfo)txtQuickSearch.getAuthInfo();
			uifId541374220056377 = (AuthInfo)Panel_16.getAuthInfo();	
			((javax.swing.JPanel)(Panel_16).getNativePanel()).setLayout(
				new FormLayout("default,88px,default,default,default,81px,default,100px,default",
								"top:default,top:default,top:default"));
			uifId561374220106786 = (AuthInfo)lblUrl1.getAuthInfo();
			uifId581374220137495 = (AuthInfo)txtServer.getAuthInfo();
			uifId601374220203585 = (AuthInfo)lblColon2.getAuthInfo();
			uifId621374220225887 = (AuthInfo)txtPort.getAuthInfo();
			uifId641374220309964 = (AuthInfo)lblColon1.getAuthInfo();
			uifId661374220341490 = (AuthInfo)txtInstance.getAuthInfo();
			uifId681374220396532 = (AuthInfo)lblUser.getAuthInfo();
			uifId701374220428131 = (AuthInfo)lblPwd.getAuthInfo();
			uifId1051380870109312 = (BindingsInfra)txtUserName.getBindings();	
			uifId1061380870109312 = new PropertyBindingInfra();
			
			uifId1061380870109312.setPropertyName("text");
			uifId1061380870109312.setModelUpdateMode(UifPropertyBinding.ModelUpdateMode.ONVALIDATION);
			uifId1061380870109312.setFieldName("user");
			uifId1061380870109312.setDataModel((UifDataModelInfra)inputDM);
			uifId1051380870109312.addPropertyBinding(uifId1061380870109312);
			uifId721374220442063 = (AuthInfo)txtUserName.getAuthInfo();
			uifId1071380870126452 = (BindingsInfra)txtPassword.getBindings();	
			uifId1081380870126452 = new PropertyBindingInfra();
			
			uifId1081380870126452.setPropertyName("text");
			uifId1081380870126452.setModelUpdateMode(UifPropertyBinding.ModelUpdateMode.ONVALIDATION);
			uifId1081380870126452.setFieldName("password");
			uifId1081380870126452.setDataModel((UifDataModelInfra)inputDM);
			uifId1071380870126452.addPropertyBinding(uifId1081380870126452);
			uifId741374220447473 = (AuthInfo)txtPassword.getAuthInfo();
			btnRead.setActionMethodName("btnRead_Action");
			uifId781374220541654 = (AuthInfo)btnRead.getAuthInfo();
			cmbOperations.setValueFieldName("value");
			cmbOperations.setListTDM((UifTabularDataModelInfra)OperationsTDM);
			cmbOperations.setDisplayFieldName("Title");
			uifId1211381229692852 = (BindingsInfra)cmbOperations.getBindings();	
			uifId1221381229692852 = new PropertyBindingInfra();
			
			uifId1221381229692852.setPropertyName("selectedText");
			uifId1221381229692852.setModelUpdateMode(UifPropertyBinding.ModelUpdateMode.ONVALIDATION);
			uifId1221381229692852.setFieldName("Operation");
			uifId1221381229692852.setDataModel((UifDataModelInfra)inputDM);
			uifId1211381229692852.addPropertyBinding(uifId1221381229692852);
			uifId761374220496891 = (AuthInfo)cmbOperations.getAuthInfo();
			uifId861374480001804 = (AuthInfo)Label_32.getAuthInfo();
			btnExpandAll.setActionMethodName("btnExpandAll_Action");
			btnExpandAll.setEnabled(false);
			uifId1591383070204400 = (AuthInfo)btnExpandAll.getAuthInfo();
			btnExport.setActionMethodName("btnExport_Action");
			btnExport.setEnabled(false);
			uifId1611383203617437 = (AuthInfo)btnExport.getAuthInfo();
			lblMessage.setStyle("RedTextBigFont");
			uifId1821384188673519 = (AuthInfo)lblMessage.getAuthInfo();
    		rootNode.setPostDataModelChangeMethodNameByForm(null ,getForm());
    	
			rootNode.setName("rootNode");
    		propertyTDM_uifId481374213725583.setPostTabularDataModelChangeMethodNameByForm(null ,getForm());
    	
			propertyTDM_uifId481374213725583.setName("propertyTDM");
    		inputDM.setPostDataModelChangeMethodNameByForm(null ,getForm());
    	
			inputDM.setName("inputDM");
    		OpDetials.setPostDataModelChangeMethodNameByForm(null ,getForm());
    	
			OpDetials.setName("OpDetials");
    		ResourceDetail.setPostDataModelChangeMethodNameByForm(null ,getForm());
    	
			ResourceDetail.setName("ResourceDetail");
    		OperationsTDM.setPostTabularDataModelChangeMethodNameByForm(null ,getForm());
    	
			OperationsTDM.setName("OperationsTDM");
    		backupOperationTDM.setPostTabularDataModelChangeMethodNameByForm(null ,getForm());
    	
			backupOperationTDM.setName("backupOperationTDM");
    		Classdetails.setPostTabularDataModelChangeMethodNameByForm(null ,getForm());
    	
			Classdetails.setName("Classdetails");
    		backends.setPostTabularDataModelChangeMethodNameByForm(null ,getForm());
    	
			backends.setName("backends");
    		uifId1701384065884167.setPostDataModelChangeMethodNameByForm(null ,getForm());
    	
    		uifId1721384065884167.setPostDataModelChangeMethodNameByForm(null ,getForm());
    	
    		MapBindingTDM.setPostTabularDataModelChangeMethodNameByForm(null ,getForm());
    	
			MapBindingTDM.setName("MapBindingTDM");
				
    	}
    	
    	
    	
    	/**
	     * Initializes properties whose values are externalized
	     */
    	protected void initTranslatableProperties()
    	{
    		
			btnAnalyse.setText(getString("uifId181374153051379.text"));
			txtQuickSearch.setToolTipText(getString("uifId501374216553776.toolTipText"));
			Panel_16.setTitle(getString("uifId521374220056305.title"));
			lblUrl1.setText(getString("uifId551374220106699.text"));
			txtServer.setToolTipText(getString("uifId571374220137438.toolTipText"));
			lblColon2.setText(getString("uifId591374220203416.text"));
			txtPort.setText(getString("uifId611374220225842.text"));
			txtPort.setToolTipText(getString("uifId611374220225842.toolTipText"));
			lblColon1.setText(getString("uifId631374220309932.text"));
			txtInstance.setToolTipText(getString("uifId651374220341490.toolTipText"));
			lblUser.setText(getString("uifId671374220396484.text"));
			lblPwd.setText(getString("uifId691374220428131.text"));
			txtUserName.setText(getString("uifId711374220441981.text"));
			txtPassword.setText(getString("uifId731374220447421.text"));
			btnRead.setText(getString("uifId771374220541588.text"));
			Label_32.setText(getString("uifId851374480001725.text"));
			btnExpandAll.setText(getString("uifId1581383070204286.text"));
			btnExport.setText(getString("uifId1601383203617409.text"));
    		
    	}

		
		/**
	     * Builds the layout of the Form
	     */    	
    	protected void buildLayout()
    	{
    		
			root.add(lblMessage ,new CellConstraints("1,4,2,1"));	
			root.add(btnExport ,new CellConstraints("4,5"));	
			root.add(btnExpandAll ,new CellConstraints("4,3"));	
			root.add(Label_32 ,new CellConstraints("1,2"));	
			root.add(cmbOperations ,new CellConstraints("1,3,2,1"));	
			Panel_16.add(btnRead ,new CellConstraints("8,3"));	
			Panel_16.add(txtPassword ,new CellConstraints("2,3"));	
			Panel_16.add(txtUserName ,new CellConstraints("2,2"));	
			Panel_16.add(lblPwd ,new CellConstraints("1,3"));	
			Panel_16.add(lblUser ,new CellConstraints("1,2"));	
			Panel_16.add(txtInstance ,new CellConstraints("6,1"));	
			Panel_16.add(lblColon1 ,new CellConstraints("3,1"));	
			Panel_16.add(txtPort ,new CellConstraints("4,1"));	
			Panel_16.add(lblColon2 ,new CellConstraints("5,1"));	
			Panel_16.add(txtServer ,new CellConstraints("2,1"));	
			Panel_16.add(lblUrl1 ,new CellConstraints("1,1"));	
			root.add(Panel_16 ,new CellConstraints("1,1,2,1"));	
			root.add(txtQuickSearch ,new CellConstraints("2,2"));	
			root.add(btnAnalyse ,new CellConstraints("3,3"));	
			root.add(treeAifOperation ,new CellConstraints("1,5,3,2"));
    	}
    	
    	
    	/**
	     * Initializes Form Event handlers
	     */
    	protected void initEventHandlerNames()
    	{
    		super.initEventHandlerNames();
    			
    		setPostOpenMethodName("form_PostOpen");
    	}
    	
    	
    	/**
	     * Initializes Form properties
	     */
    	protected void initFormProperties() 
    	{
        			
    		((UifForm)this.form).setTitle(getString("Form.title"));
    	}
    }
