    /**
     *	THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT THIS FILE.
     *
     **/ 
	package com.amdocs.bss.tool.aifAnalyser;
	import java.util.TimeZone;
	import com.amdocs.uif.datacomm.*;
	import com.amdocs.uif.action.*;
	import com.amdocs.uif.binding.*;
	import com.amdocs.uif.data.*;
	import com.amdocs.uif.widgets.*;
	import com.amdocs.uif.widgets.search.*;
	import com.amdocs.uif.widgets.search.hierarchy.*;
	import com.amdocs.uif.workspace.*;
	import com.amdocs.jgoodies.forms.layout.*;
	import amdocs.core.vo.VoFieldDef;
	import amdocs.core.vo.VoMetaData;
	import com.amdocs.uif.binding.*;
	import com.amdocs.uif.validation.*;
	import com.amdocs.uif.widgets.tree.*;
	import com.amdocs.uif.validation.*;
	import com.amdocs.uif.security.*;	
    

    public class AifAnalyserGlobal_Builder extends FormBuilder
    {


    	
    	protected	DatasetInfra dataset;
    	protected	PanelInfra root;
    	protected	ValidationInfoInfra uifId141384109186527;
    	protected	AuthInfo uifId131384109186527;
    	protected	LaunchActionInfra LaunchAifAnalyser;
    	protected	WorkspaceEvents uifId81384109174535;
    	
	    /**
	     * Constructs a new FormBuilder.
	     */
	    public AifAnalyserGlobal_Builder(AifAnalyserGlobal form)
	    {
	    	super(form);
				    	
	    	addResourceBundle("com.amdocs.bss.tool.aifAnalyser.AifAnalyserGlobal");
	    		
	    }
    	
    	
    	
    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createControls()
    	{

			root = (PanelInfra)form.getRootPanel();
			    			
    	}
    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createActionElements()
    	{

    				
    		LaunchAifAnalyser = new LaunchActionInfra(this ,"LaunchAifAnalyser");

			    			
    	}
    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createDataModels()
    	{

    			
			dataset=(DatasetInfra)form.getDataset();	
			
			    			
    	}
   	    	/**
	  * Creates the Form Control Elements
	  */
    	protected void createDataCommElements()
    	{

    		
			    			
    	}

    	
    	/**
	     * This method initializes DataModel,Tabular DataModel, Tree control properties
	     */
    	protected void preInitNonTranslatableProperties()
    	{
    		
			LaunchAifAnalyser.setPublishedName("LaunchAifAnalyser");
			root.setName("root");
    	}
    	
    	
    	/**
	     * Adds actions to the action set
	     */
    	protected void addToActionSet()
    	{
    		
    		((ActionSetInfra)this.form.getActionSet()).addAction(LaunchAifAnalyser);
    		
    	}
    	
    	
    	/**
	     * Adds controls to control set
	     */
    	protected void addToControlSet()
    	{
    		
			
    		    		
    	}
    	
    	/**
	     * Initializes App code variables
	     */
    	protected void initAppCodeVariables()
    	{
    			
    		((AifAnalyserGlobal)form).LaunchAifAnalyser = LaunchAifAnalyser;
      		
    	}
    	
    	
    	/**
	     * Initializes the properties of Form Elements 
	     */
	     
    	protected void initNonTranslatableProperties()
    	{	
			uifId81384109174535 = new WorkspaceEvents();
			
			this.setWorkspaceEvents(uifId81384109174535);
			uifId131384109186527 = (AuthInfo)LaunchAifAnalyser.getAuthInfo();
			LaunchAifAnalyser.setLogicalFormName("com.amdocs.bss.tool.aifAnalyser.AifAnalyserForm");
			LaunchAifAnalyser.setVisible(false);
			uifId141384109186527 = (ValidationInfoInfra)LaunchAifAnalyser.getValidationInfo();	
			((javax.swing.JPanel)(root).getNativePanel()).setLayout(
				new FormLayout("default,default,default,default",
								"top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default,top:default"));
				
    	}
    	
    	
    	
    	/**
	     * Initializes properties whose values are externalized
	     */
    	protected void initTranslatableProperties()
    	{
    		
    		
    	}

		
		/**
	     * Builds the layout of the Form
	     */    	
    	protected void buildLayout()
    	{
    	
    	}
    	
    	
    	/**
	     * Initializes Form Event handlers
	     */
    	protected void initEventHandlerNames()
    	{
    		super.initEventHandlerNames();
    			
    		setPostOpenMethodName("form_PostOpen");
    	}
    	
    	
    	/**
	     * Initializes Form properties
	     */
    	protected void initFormProperties() 
    	{
        			
    		((UifForm)this.form).setTitle(getString("Form.title"));
    	}
    }
